config/routes.rb
Rails.application.routes.draw do
  resources :ests
  root "ests#index"
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/est.rb
class Est < ApplicationRecord
validates_presence_of :nombre, presence: true
validates_format_of :nombre, :with => /\A[a-zA-Z]+\z/
validates :nombre, length: { maximum: 15 },on: :create
validates_presence_of :apellido, presence: true
validates_format_of :apellido, :with => /\A[a-zA-Z]+\z/
validates :apellido, length: { maximum: 15 },on: :create
validates_presence_of :carrera, presence: true
validates_format_of :carrera, :with => /\A[a-zA-Z]+\z/
validates :carrera, length: { maximum: 15 },on: :create
validates_presence_of :carnet, presence: true
validates_format_of :carnet, :with => /\A[a-zA-Z0-9-]+\z/
end

app/models/user.rb
class User < ApplicationRecord
    validates_presence_of :name, presence: true
    validates_format_of :name, :with => /\A[a-zA-Z]+\z/
    validates :name, length: { maximum: 15 },on: :create
    validates_presence_of :password, presence: true
    validates_length_of :password, is: 8
    validates_presence_of :email, presence: true
    validates_uniqueness_of :email
    validates_format_of :email, with: /@/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ests_controller.rb
class EstsController < ApplicationController
  before_action :set_est, only: %i[ show edit update destroy ]

  # GET /ests or /ests.json
  def index
    @ests = Est.all
  end

  # GET /ests/1 or /ests/1.json
  def show
  end

  # GET /ests/new
  def new
    @est = Est.new
  end

  # GET /ests/1/edit
  def edit
  end

  # POST /ests or /ests.json
  def create
    @est = Est.new(est_params)

    respond_to do |format|
      if @est.save
        format.html { redirect_to est_url(@est), notice: "Est was successfully created." }
        format.json { render :show, status: :created, location: @est }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @est.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ests/1 or /ests/1.json
  def update
    respond_to do |format|
      if @est.update(est_params)
        format.html { redirect_to est_url(@est), notice: "Est was successfully updated." }
        format.json { render :show, status: :ok, location: @est }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @est.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ests/1 or /ests/1.json
  def destroy
    @est.destroy!

    respond_to do |format|
      format.html { redirect_to ests_url, notice: "Est was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_est
      @est = Est.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def est_params
      params.require(:est).permit(:nombre, :apellido, :carrera, :carnet)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ests_helper.rb
module EstsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ests/_est.html.erb
<div id="<%= dom_id est %>">
  <p>
    <strong>Nombre:</strong>
    <%= est.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= est.apellido %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= est.carrera %>
  </p>

  <p>
    <strong>Carnet:</strong>
    <%= est.carnet %>
  </p>

</div>

app/views/ests/_form.html.erb
<%= form_with(model: est) do |form| %>
  <% if est.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(est.errors.count, "error") %> prohibited this est from being saved:</h2>

      <ul>
        <% est.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido %>
  </div>

  <div>
    <%= form.label :carrera, style: "display: block" %>
    <%= form.text_field :carrera %>
  </div>

  <div>
    <%= form.label :carnet, style: "display: block" %>
    <%= form.text_field :carnet %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ests/edit.html.erb
<h1>Editing est</h1>

<%= render "form", est: @est %>

<br>

<div>
  <%= link_to "Show this est", @est %> |
  <%= link_to "Back to ests", ests_path %>
</div>

app/views/ests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ests</h1>

<div id="ests">
  <% @ests.each do |est| %>
    <%= render est %>
    <p>
      <%= link_to "Show this est", est %>
    </p>
  <% end %>
</div>

<%= link_to "New est", new_est_path %>

app/views/ests/new.html.erb
<h1>New est</h1>

<%= render "form", est: @est %>

<br>

<div>
  <%= link_to "Back to ests", ests_path %>
</div>

app/views/ests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @est %>

<div>
  <%= link_to "Edit this est", edit_est_path(@est) %> |
  <%= link_to "Back to ests", ests_path %>

  <%= button_to "Destroy this est", @est, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppMysql</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>